# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\jwch1\Desktop\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 715)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.beforeImage = QtWidgets.QLabel(self.centralwidget)
        self.beforeImage.setGeometry(QtCore.QRect(60, 60, 241, 351))
        self.beforeImage.setAutoFillBackground(False)
        self.beforeImage.setFrameShape(QtWidgets.QFrame.Box)
        self.beforeImage.setText("")
        self.beforeImage.setTextFormat(QtCore.Qt.AutoText)
        self.beforeImage.setObjectName("beforeImage")
        self.afterImage = QtWidgets.QLabel(self.centralwidget)
        self.afterImage.setGeometry(QtCore.QRect(430, 60, 241, 351))
        self.afterImage.setFrameShape(QtWidgets.QFrame.Box)
        self.afterImage.setFrameShadow(QtWidgets.QFrame.Plain)
        self.afterImage.setText("")
        self.afterImage.setObjectName("afterImage")
        self.dial = QtWidgets.QDial(self.centralwidget)
        self.dial.setGeometry(QtCore.QRect(690, 90, 101, 101))
        self.dial.setMinimum(2)
        self.dial.setMaximum(10)
        self.dial.setPageStep(1)
        self.dial.setNotchesVisible(True)
        self.dial.setObjectName("dial")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(700, 420, 91, 41))
        self.commandLinkButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 20, 151, 41))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕 Semilight")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(480, 20, 151, 41))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕 Semilight")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(60, 430, 641, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(700, 60, 91, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕 Semilight")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(735, 130, 31, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider.setGeometry(QtCore.QRect(730, 250, 22, 160))
        self.verticalSlider.setToolTip("")
        self.verticalSlider.setToolTipDuration(5)
        self.verticalSlider.setMaximum(100)
        self.verticalSlider.setProperty("value", 100)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(710, 220, 61, 21))
        self.label_5.setObjectName("label_5")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(60, 470, 721, 181))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setObjectName("groupBox")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 111, 121))
        self.label_6.setObjectName("label_6")
        self.openDirectoryButton = QtWidgets.QPushButton(self.groupBox)
        self.openDirectoryButton.setGeometry(QtCore.QRect(630, 130, 81, 41))
        self.openDirectoryButton.setObjectName("openDirectoryButton")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(360, 60, 61, 351))
        self.listWidget.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.listWidget.setDragEnabled(True)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.listWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidget.setObjectName("listWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionGoto_gitHub = QtWidgets.QAction(MainWindow)
        self.actionGoto_gitHub.setObjectName("actionGoto_gitHub")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionGoto_gitHub)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Project1. K-means."))
        self.commandLinkButton.setText(_translate("MainWindow", "Process"))
        self.label.setText(_translate("MainWindow", "Before Image"))
        self.label_2.setText(_translate("MainWindow", "After Image"))
        self.label_3.setText(_translate("MainWindow", "Num of Cluster"))
        self.label_4.setText(_translate("MainWindow", "2"))
        self.label_5.setText(_translate("MainWindow", "Loop limit"))
        self.groupBox.setTitle(_translate("MainWindow", "Recent"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.openDirectoryButton.setText(_translate("MainWindow", "Working\n"
"directory"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionGoto_gitHub.setText(_translate("MainWindow", "Goto gitHub"))

